#
#   Author: Rohith
#   Date: 2015-07-24 15:40:40 +0100 (Fri, 24 Jul 2015)
#
#  vim:ts=2:sw=2:et
#
#
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-gateway
spec:
  replicas: 1
  selector:
    name: nginx-gateway
  template:
    metadata:
      labels:
        name: nginx-gateway
        app: nginx
        role: gateway
      metrics: |
        - name: nginx
          port: 9113
    spec:
      containers:
      - name: nginx-gateway
        image: gambol99/nginx-gateway
      - name: nginx_metrics
        image: fish/nginx-exporter
        ports:
          - containerPort: 9113
      hostNetwork: true
