#
#   Author: Rohith
#   Date: 2015-06-25 12:46:59 +0100 (Thu, 25 Jun 2015)
#
#  vim:ts=2:sw=2:et
#
apiVersion: v1beta3
kind: Service
metadata:
  labels:
    name: gitlab-web
  name: gitlab-web
  annotations:
    loadbalancer: |
      80:
        type: http
        vhost: logs.example.com
        redirect:
          path: /
          url: https://logs.example.com
      443:
        type: http
        vhost: logs.example.com
        maintenance: http://maintenance.example.com
        allowed:
          - 127.0.0.1
          - 10.0.0.0
        ssl:
          key: /etc/ssl/certs/logs.example.com.key
          cert: /etc/ssl/certs/logs.example.com.crt 
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  selector:
    name: gitlab-web
